services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bluebranch\Chatbot\:
        resource: '../../*'
        exclude: '../../{Resources,DependencyInjection,Model,Tests,Migrations}'

    Bluebranch\Chatbot\EventListener\IndexPageListener:
        public: true

    Bluebranch\Chatbot\classes\ChatbotAPI:
        public: true

    Bluebranch\Chatbot\Controller\Backend\TrainedContentController:
        public: true

    Bluebranch\Chatbot\classes\ContentIndexerCallbackListener:
        public: true

